/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exerc8;

import java.util.Scanner;
import java.util.logging.Logger;

public class App {

    private static final Logger logger = Logger.getLogger(App.class.getName()); 
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        while(true){
            logger.info("Insira um numero: ");
            String numString = scanner.nextLine();
            try {
                int num = Integer.parseInt(numString);
                if (num == 10) break;
            } catch(NumberFormatException ex) {
                logger.warning("Entrada invalida.");
            }
        }
        logger.info("Programa encerrado.");
    }
}
