/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exerc2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("Insira o nome do Produto: ");
        String nome = scanner.nextLine();

        System.out.println("Insira o Preco do Produto: ");
        String preco = scanner.nextLine();

        System.out.println("Insira a Quantidade do Produto: ");
        String quantidade = scanner.nextLine();

        try {
            double precoDouble = Double.parseDouble(preco);
            int quantidadeInt = Integer.parseInt(quantidade);
            Produto produto = new Produto(nome, precoDouble, quantidadeInt);

        } catch (NumberFormatException ex) {

        } catch (ExcecaoParametroInvalido ex) {
            System.out.println("Parâmetro Inválido: " + ex.getMessage());
        }
    }
}
